build:
  version: "2.0"

loans:
  message: "Welcome to EazyBank loans related QA APIs "
  contactDetails:
    name: "Pavan - QA"
    email: "pavan@eazybank.com"
  onCallSupport:
    - (999) 456-2176
    - (999) 764-8934