spring:
  config:
    activate:
      on-profile: "qa"
build:
  version: 2.0
cards:
  message: "Welcome to EazyBank cards related QA APIs "
  contactDetails:
    name: "Justin - QA"
    email: "justin@eazybank.com"
  onCallSupport:
    - (678) 419-3491
    - (923) 382-1932