server:
  port:8080
spring:
  config:
    import: "optional:configserver:http://localhost:8071/"
  application:
   name: "accounts"
  profiles:
   active: "prod"
  datasource:
    url: jdbc:mysql://localhost:3309/accountsdb
    username: root
    password: root
  jpa:
      show-sql: true
  sql:
    init:
      mode: always
management:
  endpoints:
    web:
      exposure:
        include: "*"

build:
  version: "1.0"
